name: Python Calculator

on:
  push:
    branches: [main, development, release]
  pull_request:
    branches: [main, development, release]   
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdoc

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest -q

      - name: Build docs
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pdoc calculator -o docs

      - name: Commit docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update docs [skip ci]" || echo "No changes to commit"
          git push
